import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screenContainer: {
    flexGrow: 1,
    backgroundColor: '#F4F6F5',
    alignItems: 'center',
    padding: 0,
    gap: 16,
    minHeight: 805,
    position: 'relative',
    isolation: 'isolate',
  },
  loaderContainer: {
    flex: 1,
    backgroundColor: '#e8f0e8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    width: "100%",
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingHorizontal: 16,
    paddingTop: 24,
    gap: 10,
    marginBottom: 8,
  },
  backButton: {
    width: 160,
    height: 15,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#59695C',
  },
  backButtonText: {
    fontFamily: 'Inter',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 15,
    letterSpacing: -0.02,
    color: '#59695C',
  },
  cardContainer: {
    width: '100%',
    maxWidth: 358,
    minHeight: 646,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#224229',
    borderRadius: 24,
    boxShadow: '4px 4px 0px #224229',
    shadowColor: '#224229',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 0,
    elevation: 4,
    padding: 24,
    gap: 16,
    alignItems: 'flex-start',
    marginTop: 16,
    alignSelf: 'center',
    marginHorizontal: 16,
  },
  imageFrame: {
    width: '100%',
    maxWidth: 310,
    height: 310,
    borderWidth: 1,
    borderColor: '#224229',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 16,
    alignSelf: 'center',
  },
  characterImage: {
    width: '100%',
    maxWidth: 310,
    height: 310,
    borderRadius: 24,
    resizeMode: 'cover',
    alignSelf: 'center',
  },
  cardText: {
    width: "100%",
    gap: 16,
  },
  mainFeature: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: 8,
    gap: 4,
    width: "100%",
    height: 80,
  },
  label: {
    fontFamily: 'DM Mono',
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.08,
    textTransform: 'uppercase',
    color: '#59695C',
  },
  name: {
    fontFamily: 'Inter',
    fontWeight: '500',
    fontSize: 36,
    lineHeight: 44,
    letterSpacing: -0.06,
    color: '#162C1B',
    marginTop: 4,
  },
  secondaryFeatures: {
    flexDirection: 'column',
    gap: 16,
    width: "100%",
    height: 126,
  },
  featuresRow: {
    flexDirection: 'row',
    gap: 16,
    width: "100%",
    height: 55,
  },
  featureBox: {
    flex: 1,
    backgroundColor: '#F4F6F5',
    borderWidth: 1,
    borderColor: '#F4F6F5',
    borderRadius: 10,
    padding: 8,
    gap: 4,
    minWidth: 147,
    minHeight: 55,
  },
  featureValue: {
    fontFamily: 'Inter',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 19,
    letterSpacing: -0.02,
    color: '#162C1B',
  },
  likeButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    gap: 4,
    width: "100%",
    height: 34,
    backgroundColor: '#224229',
    borderRadius: 100,
    marginTop: 16,
  },
  likeIcon: {
    color: '#fff',
    fontSize: 16,
    marginRight: 8,
  },
  likeButtonText: {
    fontFamily: 'DM Mono',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 18,
    textTransform: 'uppercase',
    color: '#fff',
  },
});