import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  cardWrapper: {
    position: 'relative',
    marginVertical: 16,
    alignSelf: 'center',
  },
  leftCol: {
    flex: 1,
    justifyContent: 'center',
    gap: 12,
  },
  label: {
    fontFamily: 'DM Mono',
    fontWeight: '500',
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#59695C',
    marginBottom: 2,
  },
  value: {
    fontFamily: 'Inter',
    fontWeight: '400',
    fontSize: 18,
    lineHeight: 22,
    color: '#162C1B',
    marginBottom: 4,
  },
  rightCol: {
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 16,
    position: 'relative',
  },
  imageFrame: {
    width: 200,
    height: 200,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#224229',
    overflow: 'hidden',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    width: 200,
    height: 200,
    resizeMode: 'cover',
    borderRadius: 10,
  },
  likeButton: {
    position: 'absolute',
    bottom: 8,
    left: '75%',
    transform: [{ translateX: -41 }],
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderColor: '#224229',
    borderWidth: 1,
    borderRadius: 16,
    paddingVertical: 4,
    paddingHorizontal: 12,
    shadowColor: '#224229',
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.10,
    shadowRadius: 2,
    elevation: 2,
    zIndex: 2,
  },
  likeIcon: {
    fontSize: 18,
    marginRight: 6,
  },
  likeText: {
    fontFamily: 'DM Mono',
    fontWeight: '400',
    fontSize: 13,
    lineHeight: 18,
    textTransform: 'uppercase',
    color: '#224229',
  },
  header: {
    alignItems: 'flex-start',
    marginTop: 32,
    marginBottom: 16
  },
  headerContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingHorizontal: 16,
    gap: 16,
    width: '100%',
    zIndex: 2,
    marginBottom: 8,
    marginTop: 8,
  },
  cardShadow: {
    position: 'absolute',
    top: 6,
    left: 6,
    width: '100%',
    maxWidth: 340,
    height: 140,
    backgroundColor: 'rgba(34,66,41,0.12)',
    borderRadius: 16,
    zIndex: 0,
  },
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    maxWidth: 340,
    minHeight: 140,
    backgroundColor: '#F4F6F5',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#224229',
    padding: 16,
    zIndex: 1,
    shadowColor: '#224229',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 0,
    elevation: 4,
    fontSize: 16
  },
  headerTitle: {
    width: 172,
    height: 44,
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 36,
    lineHeight: 44,
    letterSpacing: -0.06 * 36,
    color: '#162C1B',
  },
  searchBarInner: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: 46,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#162C1B',
    borderRadius: 100,
    paddingHorizontal: 12,
  },
  searchIcon: {
    width: 20,
    height: 20,
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 19,
    letterSpacing: -0.02 * 16,
    color: '#162C1B',
    paddingVertical: 0,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  filterButtonInner: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: '#224229',
    borderRadius: 22,
    width: 113,
    height: 34,
  },
  filterButtonText: {
    fontFamily: 'DM Mono',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 18,
    textTransform: 'uppercase',
    color: '#FFFFFF',
  },
  filterButtonIcon: {
    color: '#FFFFFF',
    alignSelf: 'center',
  },
  filterIconContainer: {
    marginLeft: 8,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
});