import { StyleSheet } from 'react-native';

export const filterPanelStyles = StyleSheet.create({
    panel: {
        width: '100%',
        backgroundColor: '#fff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#224229',
        padding: 16,
        shadowColor: '#224229',
        shadowOffset: { width: 4, height: 4 },
        shadowOpacity: 1,
        shadowRadius: 0,
        elevation: 4,
        marginTop: 8,
        marginBottom: 8,
    },
    section: {
        marginBottom: 24,
    },
    sectionLabel: {
        fontFamily: 'DM Mono',
        fontWeight: '500',
        fontSize: 14,
        color: '#59695C',
        textTransform: 'uppercase',
        marginBottom: 8,
    },
    optionsColumn: {
        flexDirection: 'column',
    },
    optionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    optionText: {
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#162C1B',
        letterSpacing: -0.02 * 16,
    },
    checkbox: {
        width: 16,
        height: 16,
        borderRadius: 4,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 8,
    },
    buttonsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    resetButton: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 100,
        borderWidth: 1,
        borderColor: '#224229',
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        width: 100,
    },
    resetButtonText: {
        fontFamily: 'DM Mono',
        fontSize: 14,
        color: '#224229',
        textTransform: 'uppercase',
        textAlign: 'center',
    },
    applyButton: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 100,
        backgroundColor: '#224229',
        alignItems: 'center',
        justifyContent: 'center',
        width: 100,
    },
    applyButtonText: {
        fontFamily: 'DM Mono',
        fontSize: 14,
        color: '#fff',
        textTransform: 'uppercase',
        textAlign: 'center',
    },
});